// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThingMan.Core.SqlDB;

#nullable disable

namespace ThingMan.Core.SqlDB.Migrations.ThingMan
{
    [DbContext(typeof(ThingManDbContext))]
    partial class ThingManDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("ThingMan.Core.SqlDB.Entities.PropertyDefEntity", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PropertyDef");
                });

            modelBuilder.Entity("ThingMan.Core.SqlDB.Entities.StatusDefEntity", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThingDefEntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThingDefEntityId");

                    b.ToTable("StatusDef");
                });

            modelBuilder.Entity("ThingMan.Core.SqlDB.Entities.ThingDefEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PropertyDef1Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PropertyDef2Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PropertyDef3Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PropertyDef4Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PropertyDef5Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyDef1Id");

                    b.HasIndex("PropertyDef2Id");

                    b.HasIndex("PropertyDef3Id");

                    b.HasIndex("PropertyDef4Id");

                    b.HasIndex("PropertyDef5Id");

                    b.ToTable("ThingDef");
                });

            modelBuilder.Entity("ThingMan.Core.SqlDB.Entities.StatusDefEntity", b =>
                {
                    b.HasOne("ThingMan.Core.SqlDB.Entities.ThingDefEntity", null)
                        .WithMany("StatusDefs")
                        .HasForeignKey("ThingDefEntityId");
                });

            modelBuilder.Entity("ThingMan.Core.SqlDB.Entities.ThingDefEntity", b =>
                {
                    b.HasOne("ThingMan.Core.SqlDB.Entities.PropertyDefEntity", "PropertyDef1")
                        .WithMany()
                        .HasForeignKey("PropertyDef1Id");

                    b.HasOne("ThingMan.Core.SqlDB.Entities.PropertyDefEntity", "PropertyDef2")
                        .WithMany()
                        .HasForeignKey("PropertyDef2Id");

                    b.HasOne("ThingMan.Core.SqlDB.Entities.PropertyDefEntity", "PropertyDef3")
                        .WithMany()
                        .HasForeignKey("PropertyDef3Id");

                    b.HasOne("ThingMan.Core.SqlDB.Entities.PropertyDefEntity", "PropertyDef4")
                        .WithMany()
                        .HasForeignKey("PropertyDef4Id");

                    b.HasOne("ThingMan.Core.SqlDB.Entities.PropertyDefEntity", "PropertyDef5")
                        .WithMany()
                        .HasForeignKey("PropertyDef5Id");

                    b.Navigation("PropertyDef1");

                    b.Navigation("PropertyDef2");

                    b.Navigation("PropertyDef3");

                    b.Navigation("PropertyDef4");

                    b.Navigation("PropertyDef5");
                });

            modelBuilder.Entity("ThingMan.Core.SqlDB.Entities.ThingDefEntity", b =>
                {
                    b.Navigation("StatusDefs");
                });
#pragma warning restore 612, 618
        }
    }
}
